### ISSUE TITLE
Re-evaluate backup solution

### ISSUE THREAD

**Issue by suorcd** [podverse/podverse-ops#21]
The current solution streams the data to gzip (with default level 6 compression) to a separate xfs block storage device.
The result is a fairly well compressed sql file; with about 90G of saving
The pv-db it took about 8 hours with the current solution

Looking around this might be a viable option https://serverfault.com/questions/1081642/postgresql-13-speed-up-pg-dump-to-5-minutes-instead-of-70-minutes

Also looking into adding the fast flag, streaming the data uncompressed to the volume and then compressing, or moving over to something like zstd

**Comment by suorcd** [comment]
Using the aforementioned’s link option, on my spinning rust with zfs mirrored raid over usb3 connect it took about 6 hours to dump and compress; on the fly compression was turned on. The server is fairly busy and old.

**Comment by suorcd** [comment]
Switching to the tar.gz option is not supported by the automatic postgres init db ingestion so a manual pg_restore would be required.

**Comment by suorcd** [comment]
One article says there is decent speed improvements with zstd https://thedatafreak.medium.com/parquet-zstd-vs-gzip-740a83571ecd

**Comment by suorcd** [comment]
Looks like we could write an .sh script to pull in the binary data

```bash
…
                        *.sh)
                                # https://github.com/docker-library/postgres/issues/450#issuecomment-393167936
                                # https://github.com/docker-library/postgres/pull/452
                                if [ -x "$f" ]; then
                                        echo "$0: running $f"
                                        "$f"
                                else
                                        echo "$0: sourcing $f"
                                        . "$f"
                                fi
                                ;;
                        *.sql)     echo "$0: running $f"; docker_process_sql -f "$f"; echo ;;
                        *.sql.gz)  echo "$0: running $f"; gunzip -c "$f" | docker_process_sql; echo ;;
                        *.sql.xz)  echo "$0: running $f"; xzcat "$f" | docker_process_sql; echo ;;
                        *.sql.zst) echo "$0: running $f"; zstd -dc "$f" | docker_process_sql; echo ;;
                        *)         echo "$0: ignoring $f" ;;
```

**Comment by suorcd** [comment]
@mitchdowney do you have a preference .sql text file or tar binary files?

I like .sql since it can be inspected, but binary can be a bit more robust

**Comment by mitchdowney** [comment]
@suorcd I don't have a preference. I don't really have the knowledge to have a preference either way. I'd vote for whatever you like most / feel most comfortable with.

**Comment by suorcd** [comment]
As discussed int chat, moving the DB dump time to 07:00 UTC (23:00 PST); starting tomorrow.

**Comment by suorcd** [comment]
Sticking with the .sql file for now; ran an import test, locally, using the tar file and results weren't good over 1000 minute import.
Probably got a couple settings wrong.

**Comment by suorcd** [comment]
After running various compression tests locally zstd was the clear winner.
It compressed the file in about a third the time and was several gigs smaller than the default gzip test.

**Comment by suorcd** [comment]
After several tests and a couple days, so far the changes are:
* move the start time to 5:00UTC; an hour later might be more ideal, but i want to give plenty of time before the manticore job
* remove the 5:30UTC manticore job, since the rotate jobs are full each time it won’t make the later jobs longer and it is a quieter time so refreshing the index isn’t as important
* switch to zstd, smaller files (about 9GB smaller than current gzip) and faster compression/decompression

**Comment by suorcd** [comment]
This has been completed. We are able to lock down the db even more, and only make the request for data once.

**Comment by suorcd** [comment]
Next step is to update the backup script to better utilize variables and then  update the git file to reflect current reality,

**Comment by suorcd** [comment]
Once https://github.com/podverse/podverse-ops/pull/25 is approved and merged, this ticket can be closed,
